title: Jaikishan's Blog
author: Jaikishan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am software engineer working in Java, Spring framework. This page is work in progress.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jaikishangurav # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
